volumes:
    mysql_data:

services:
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "8888:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]

    minitwit:
        image: youruser/minitwitimage:latest
        ports:
            - "5001:5000"
        deploy:
            replicas: 2

    itusqlimage:
        image: mariadb:10.6
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=megetsikkertkodeord
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/minitwit/minitwit_init.sql:/docker-entrypoint-initdb.d/init.sql
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
